using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;

namespace StadiaStudio {
    public static class Ui {
        public static Color Color(string value){return (Color)ColorConverter.ConvertFromString(value);}
        public static SolidColorBrush Brush(string value){SolidColorBrush b=new SolidColorBrush(Color(value));b.Freeze();return b;}
        public static readonly Brush Background=Brush("#101517"),Panel=Brush("#1A2225"),Inset=Brush("#131B1E"),Line=Brush("#303B3F"),Text=Brush("#E9EEEB"),Muted=Brush("#98AAA9"),Lime=Brush("#CAF57A"),Coral=Brush("#FF8A70");
        public static TextBlock T(string text,double size,Brush color=null,bool bold=false) {
            TextBlock block=new TextBlock{Text=I18n.T(text),FontSize=size,Foreground=color??Text,FontWeight=bold?FontWeights.SemiBold:FontWeights.Normal,TextWrapping=TextWrapping.Wrap};I18n.Remember(block,text);return block;
        }
        public static Border Card(UIElement child,int padding=24) {
            Border card=new Border{Background=Panel,BorderBrush=Line,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(18),Padding=new Thickness(padding),Child=child};
            SolidColorBrush edge=new SolidColorBrush(Color("#303B3F"));card.BorderBrush=edge;
            card.MouseEnter+=(s,e)=>{if(SystemParameters.ClientAreaAnimation)edge.BeginAnimation(SolidColorBrush.ColorProperty,new ColorAnimation(Color("#607B68"),TimeSpan.FromMilliseconds(150)));else edge.Color=Color("#607B68");};
            card.MouseLeave+=(s,e)=>{if(SystemParameters.ClientAreaAnimation)edge.BeginAnimation(SolidColorBrush.ColorProperty,new ColorAnimation(Color("#303B3F"),TimeSpan.FromMilliseconds(180)));else edge.Color=Color("#303B3F");};
            return card;
        }
        public static void Enter(FrameworkElement view) {
            if(!SystemParameters.ClientAreaAnimation)return;
            TranslateTransform shift=new TranslateTransform();view.RenderTransform=shift;
            view.BeginAnimation(UIElement.OpacityProperty,new DoubleAnimation(.35,1,TimeSpan.FromMilliseconds(160)){EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});
            shift.BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(6,0,TimeSpan.FromMilliseconds(180)){EasingFunction=new QuadraticEase{EasingMode=EasingMode.EaseOut}});
        }
        public static Button Button(string label,Action click,bool accent=false) {
            Button b=new Button{Content=I18n.T(label),MinHeight=40,Padding=new Thickness(17,8,17,8),Background=accent?Lime:Inset,Foreground=accent?Background:Text,
                BorderBrush=accent?Lime:Line,FontSize=13,FontWeight=FontWeights.SemiBold,Cursor=System.Windows.Input.Cursors.Hand};
            ScaleTransform scale=new ScaleTransform(1,1);b.RenderTransform=scale;b.RenderTransformOrigin=new Point(.5,.5);
            b.PreviewMouseLeftButtonDown+=(s,e)=>{if(!SystemParameters.ClientAreaAnimation)return;scale.BeginAnimation(ScaleTransform.ScaleXProperty,new DoubleAnimation(.97,TimeSpan.FromMilliseconds(70)));scale.BeginAnimation(ScaleTransform.ScaleYProperty,new DoubleAnimation(.97,TimeSpan.FromMilliseconds(70)));};
            b.PreviewMouseLeftButtonUp+=(s,e)=>Release(scale);b.MouseLeave+=(s,e)=>Release(scale);
            I18n.Remember(b,label);b.Click+=(s,e)=>click();return b;
        }
        static void Release(ScaleTransform scale){if(!SystemParameters.ClientAreaAnimation){scale.BeginAnimation(ScaleTransform.ScaleXProperty,null);scale.BeginAnimation(ScaleTransform.ScaleYProperty,null);scale.ScaleX=scale.ScaleY=1;return;}scale.BeginAnimation(ScaleTransform.ScaleXProperty,new DoubleAnimation(1,TimeSpan.FromMilliseconds(120)));scale.BeginAnimation(ScaleTransform.ScaleYProperty,new DoubleAnimation(1,TimeSpan.FromMilliseconds(120)));}
        public static void Styles(ResourceDictionary resources) {
            const string xaml=@"<ResourceDictionary xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
<Style TargetType='Button'><Setter Property='BorderThickness' Value='1'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Button'><Border x:Name='B' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}' CornerRadius='10' Padding='{TemplateBinding Padding}'><ContentPresenter HorizontalAlignment='Center' VerticalAlignment='Center'/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='B' Property='Opacity' Value='.8'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter TargetName='B' Property='Opacity' Value='.4'/></Trigger><Trigger Property='IsKeyboardFocused' Value='True'><Setter TargetName='B' Property='BorderBrush' Value='#CAF57A'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ComboBox'><Setter Property='Foreground' Value='#E9EEEB'/><Setter Property='Background' Value='#131B1E'/><Setter Property='BorderBrush' Value='#303B3F'/><Setter Property='Padding' Value='12,8'/><Setter Property='MinHeight' Value='38'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ComboBox'><Grid><ToggleButton x:Name='Toggle' IsChecked='{Binding IsDropDownOpen,RelativeSource={RelativeSource TemplatedParent},Mode=TwoWay}' Focusable='False' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' Foreground='{TemplateBinding Foreground}'><ToggleButton.Template><ControlTemplate TargetType='ToggleButton'><Border Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='1' CornerRadius='8'><TextBlock Text='⌄' HorizontalAlignment='Right' VerticalAlignment='Center' Margin='0,0,12,0' Foreground='#98AAA9'/></Border></ControlTemplate></ToggleButton.Template></ToggleButton><ContentPresenter Content='{TemplateBinding SelectionBoxItem}' ContentTemplate='{TemplateBinding SelectionBoxItemTemplate}' Margin='12,8,30,8' IsHitTestVisible='False' VerticalAlignment='Center'/><Popup x:Name='PART_Popup' IsOpen='{TemplateBinding IsDropDownOpen}' Placement='Bottom' AllowsTransparency='True' Focusable='False'><Border Background='#202A2E' BorderBrush='#46554F' BorderThickness='1' CornerRadius='8' Padding='4' MinWidth='{Binding ActualWidth,RelativeSource={RelativeSource TemplatedParent}}'><ScrollViewer MaxHeight='320'><ItemsPresenter/></ScrollViewer></Border></Popup></Grid></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ComboBoxItem'><Setter Property='Foreground' Value='#E9EEEB'/><Setter Property='Padding' Value='10,7'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ComboBoxItem'><Border x:Name='B' Padding='{TemplateBinding Padding}' CornerRadius='5'><ContentPresenter/></Border><ControlTemplate.Triggers><Trigger Property='IsHighlighted' Value='True'><Setter TargetName='B' Property='Background' Value='#3D4D42'/></Trigger><Trigger Property='IsSelected' Value='True'><Setter TargetName='B' Property='Background' Value='#3D4D42'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='TextBox'><Setter Property='Background' Value='#131B1E'/><Setter Property='Foreground' Value='#E9EEEB'/><Setter Property='BorderBrush' Value='#303B3F'/><Setter Property='CaretBrush' Value='#CAF57A'/><Setter Property='Padding' Value='12,9'/><Setter Property='FontSize' Value='14'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='TextBox'><Border Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='1' CornerRadius='8' Padding='{TemplateBinding Padding}'><ScrollViewer x:Name='PART_ContentHost'/></Border></ControlTemplate></Setter.Value></Setter></Style>

<Style TargetType='Slider'><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Slider'><Grid Height='22'><Track x:Name='PART_Track' Minimum='{TemplateBinding Minimum}' Maximum='{TemplateBinding Maximum}' Value='{TemplateBinding Value}'><Track.DecreaseRepeatButton><RepeatButton Command='Slider.DecreaseLarge' Focusable='False'><RepeatButton.Template><ControlTemplate><Border Height='4' CornerRadius='2' Background='#CAF57A'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.DecreaseRepeatButton><Track.IncreaseRepeatButton><RepeatButton Command='Slider.IncreaseLarge' Focusable='False'><RepeatButton.Template><ControlTemplate><Border Height='4' CornerRadius='2' Background='#3B494B'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.IncreaseRepeatButton><Track.Thumb><Thumb Width='16' Height='16' Cursor='Hand'><Thumb.Template><ControlTemplate><Ellipse Fill='#CAF57A' Stroke='#101517' StrokeThickness='2'/></ControlTemplate></Thumb.Template></Thumb></Track.Thumb></Track></Grid></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='CheckBox'><Setter Property='Foreground' Value='#E9EEEB'/><Setter Property='Margin' Value='0,10,0,0'/><Setter Property='FontSize' Value='13'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='CheckBox'><StackPanel Orientation='Horizontal'><Border x:Name='Box' Width='18' Height='18' Background='#131B1E' BorderBrush='#52625A' BorderThickness='1' CornerRadius='4'><TextBlock x:Name='Tick' Text='✓' Visibility='Collapsed' Foreground='#101517' HorizontalAlignment='Center' VerticalAlignment='Center' FontWeight='Bold'/></Border><ContentPresenter Margin='9,0,0,0' VerticalAlignment='Center'/></StackPanel><ControlTemplate.Triggers><Trigger Property='IsChecked' Value='True'><Setter TargetName='Box' Property='Background' Value='#CAF57A'/><Setter TargetName='Box' Property='BorderBrush' Value='#CAF57A'/><Setter TargetName='Tick' Property='Visibility' Value='Visible'/></Trigger><Trigger Property='IsKeyboardFocused' Value='True'><Setter TargetName='Box' Property='BorderBrush' Value='#CAF57A'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ScrollBar'><Setter Property='Width' Value='12'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ScrollBar'><Grid Background='Transparent' Margin='2,4'><Track x:Name='PART_Track' IsDirectionReversed='True' Orientation='Vertical' Minimum='{TemplateBinding Minimum}' Maximum='{TemplateBinding Maximum}' Value='{TemplateBinding Value}' ViewportSize='{TemplateBinding ViewportSize}'><Track.DecreaseRepeatButton><RepeatButton Command='ScrollBar.PageUpCommand' Focusable='False'><RepeatButton.Template><ControlTemplate><Border Background='Transparent'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.DecreaseRepeatButton><Track.IncreaseRepeatButton><RepeatButton Command='ScrollBar.PageDownCommand' Focusable='False'><RepeatButton.Template><ControlTemplate><Border Background='Transparent'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.IncreaseRepeatButton><Track.Thumb><Thumb MinHeight='28' Background='#52645D'><Thumb.Template><ControlTemplate TargetType='Thumb'><Border x:Name='Grip' Background='{TemplateBinding Background}' CornerRadius='3' Margin='1,0'/><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='Grip' Property='Background' Value='#91AD9B'/></Trigger><Trigger Property='IsDragging' Value='True'><Setter TargetName='Grip' Property='Background' Value='#CAF57A'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Thumb.Template></Thumb></Track.Thumb></Track></Grid></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ScrollViewer'><Setter Property='Padding' Value='0,0,10,0'/><Setter Property='VerticalScrollBarVisibility' Value='Auto'/><Setter Property='HorizontalScrollBarVisibility' Value='Disabled'/></Style>
</ResourceDictionary>";
            resources.MergedDictionaries.Add((ResourceDictionary)XamlReader.Parse(xaml));
        }
        public static FrameworkElement Gap(int pixels){return new Border{Height=pixels};}
        public static FrameworkElement Logo(double size){
            Canvas c=new Canvas{Width=64,Height=64};Brush ink=new LinearGradientBrush(Color("#CAF57A"),Color("#66D9CB"),45);
            // Two angular links with an open center: original geometry, no Stadia mark.
            foreach(string data in new[]{"M31 12 L18 12 L8 24 L18 36 L30 36","M33 52 L46 52 L56 40 L46 28 L34 28","M25 42 L39 22"})c.Children.Add(new System.Windows.Shapes.Path{Data=Geometry.Parse(data),Stroke=ink,StrokeThickness=6,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round,StrokeLineJoin=PenLineJoin.Round});
            return new Viewbox{Width=size,Height=size,Child=c,HorizontalAlignment=HorizontalAlignment.Left};
        }
    }
}
